# ワークフロー名
name: housework_bot
on:
  schedule:
    # 定期実行する時間 30分おきを指定
    - cron: '30 * * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Hello world
        run: |
          # ここでファイルの操作とかできるらしい。
          # 一旦30分起きに Hello world! させてみる
          echo "Hello world!"